# Generated by Django 3.0.5 on 2020-05-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0005_auto_20200511_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='writer',
            field=models.CharField(max_length=20),
        ),
    ]
